name: "Good Workflow"

on:
  push:
    branches: ["development"]

jobs:
  test-dev:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"  

      - name: "Restore dependencies"
        run: dotnet restore
      
      - name: "Build project"
        run: dotnet build --configuration Release --no-restore
      
      - name: "Run unit tests"
        run: dotnet test --configuration Release --no-build 

  build-dev:
    runs-on: self-hosted
    needs: test-dev
    steps:
      - uses: actions/checkout@v4

      - name: "Build docker image"
        run: |
          docker build -t ${{ secrets.IMAGE_TAG }} .
          docker image prune -f   

      - name: "Check images"
        run: docker image ls

  deploy-dev:
    runs-on: self-hosted
    needs: build-dev
    steps:
      - uses: actions/checkout@v4

      - name: "Stop previous container if exists"
        run: |
          docker stop ${{ secrets.CONTAINER_NAME }} || true
          docker rm ${{ secrets.CONTAINER_NAME }} || true

      - name: "Run new container"
        run: |
          docker run -d \
            -p ${{ secrets.HOST_PORT }}:${{ secrets.CONTAINER_PORT }} \
            --name ${{ secrets.CONTAINER_NAME }} \
            ${{ secrets.IMAGE_TAG }}
